version: '3.7'

services:
  api:
    build: .
    restart: always
    image: beratuyanik.com-api:prod
    command: >
      bash -c "python /Backend/manage.py makemigrations &&
       python /Backend/manage.py migrate &&
        echo yes | python /Backend/manage.py collectstatic &&
         python /Backend/manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST : 'db'
      DB_NAME : 'beratuyanik.com'
      DB_USER : 'berat'
      DB_PASS : 'beratuyanik.com'
    ports:
      - "8000:8000"
    volumes:
      - .:/app/